#!/bin/sh

STATUS="`xrandr --current | grep HDMI1 | cut -d \  -f 2`"

if [[ "$STATUS" == "disconnected" ]] ; then
    # switch HDMI off and LVDS on
    xrandr --output HDMI1 --off
    xrandr --output eDP1 --mode 1366x768
else
    #xrandr
    xrandr --output eDP1 --primary --mode 1366x768  --output HDMI1 --mode 1360x768 --right-of eDP1
fi

