#!/usr/bin/python
# Requires "requests" to be installed (see python-requests.org)
import requests
import sys



if __name__ == '__main__':
    if len(sys.argv) != 3:
        print("Pehla edit wali image pachi unu naam")
    else:
        input_image = sys.argv[1]
        output_image = sys.argv[2]

        response = requests.post(
            'https://api.remove.bg/v1.0/removebg',
            files={'image_file': open(input_image, 'rb')},
            data={'size': 'auto'},
            headers={'X-Api-Key': 'ckvuj4Ut516PBCDLQNfUvAhW'},
        )
        if response.status_code == requests.codes.ok:
            with open(output_image, 'wb') as out:
                out.write(response.content)
        else:
            print("Error:", response.status_code, response.text)


