#! /bin/bash

notify-send.sh "Enter Your Password"
PASS=$(echo "" | dmenu -l 5 -i  -fn 'Hack:bold:pixelsize=0')
NAME=$(openssl enc -e -aes256 -d -in ~/Password -pass "pass:$PASS"| awk '{print $1}' | dmenu -l 5 -i -nb '#191919' )

openssl enc -e -aes256 -d -in ~/Password -pass "pass:$PASS"| grep $NAME | awk '{print $2}'  | xsel -b && notify-send.sh "$NAME copied !!!"
